<?php
namespace app\api\controller;
use My\DataReturn;
use think\Exception;

class Imgresources extends Base{

	//小程序图片
	public function index(){
		$prefix = request()->domain();
		$res = array();
		$res = [
			'images_1' => $prefix ."/smallprogramimg/3_07.png",
			'images_2' => $prefix ."/smallprogramimg/6_03.png",
			'images_3' => $prefix ."/smallprogramimg/7_03.jpg",
			'images_4' => $prefix ."/smallprogramimg/8_03.jpg",
			'images_5' => $prefix ."/smallprogramimg/8_03.png",
			'images_6' => $prefix ."/smallprogramimg/8_13.png",
			'images_7' => $prefix ."/smallprogramimg/9_03.png",
			'images_8' => $prefix ."/smallprogramimg/10_03.png",
			'images_9' => $prefix ."/smallprogramimg/17_03.png",
			'images_10' => $prefix ."/smallprogramimg/18_03.jpg",
			'images_11' => $prefix ."/smallprogramimg/18_05.jpg",
			'images_12' => $prefix ."/smallprogramimg/20_19.png",
			'images_13' => $prefix ."/smallprogramimg/404.png",
			'images_14' => $prefix ."/smallprogramimg/a4_03.png",
			'images_15' => $prefix ."/smallprogramimg/arrowd.png",
			'images_16' => $prefix ."/smallprogramimg/arrowd1.png",
			'images_17' => $prefix ."/smallprogramimg/arrowd2.png",
			'images_18' => $prefix ."/smallprogramimg/arrowd3.png",
			'images_19' => $prefix ."/smallprogramimg/cardbottom.png",
			'images_20' => $prefix ."/smallprogramimg/chongznok.png",
			'images_21' => $prefix ."/smallprogramimg/chongzok.png",
			'images_22' => $prefix ."/smallprogramimg/copylink.png",
			'images_23' => $prefix ."/smallprogramimg/coupon.png",
			'images_24' => $prefix ."/smallprogramimg/couponbg.png",
			'images_25' => $prefix ."/smallprogramimg/couponbgr.png",
			'images_26' => $prefix ."/smallprogramimg/currnumber.png",
			'images_27' => $prefix ."/smallprogramimg/daizf.png",
			'images_28' => $prefix ."/smallprogramimg/dd_icon_01.png",
			'images_29' => $prefix ."/smallprogramimg/dd_icon_02.png",
			'images_30' => $prefix ."/smallprogramimg/dd_icon_03.png",
			'images_31' => $prefix ."/smallprogramimg/dd_icon_04.png",
			'images_32' => $prefix ."/smallprogramimg/dd_icon_05.png",
			'images_33' => $prefix ."/smallprogramimg/delfile.png",
			'images_34' => $prefix ."/smallprogramimg/df-avatar.png",
			'images_35' => $prefix ."/smallprogramimg/dh_icon01.png",
			'images_36' => $prefix ."/smallprogramimg/dh_icon02.png",
			'images_37' => $prefix ."/smallprogramimg/dh_icon03.png",
			'images_38' => $prefix ."/smallprogramimg/dp_icon_01.png",
			'images_39' => $prefix ."/smallprogramimg/dp_icon_02.png",
			'images_40' => $prefix ."/smallprogramimg/expired.png",
			'images_41' => $prefix ."/smallprogramimg/eye-close.png",
			'images_42' => $prefix ."/smallprogramimg/eye-eye-open.png",
			'images_43' => $prefix ."/smallprogramimg/fx_icon1.png",
			'images_44' => $prefix ."/smallprogramimg/fx_icon2.png",
			'images_45' => $prefix ."/smallprogramimg/fx_icon3.png",
			'images_46' => $prefix ."/smallprogramimg/fx_icon4.png",
			'images_47' => $prefix ."/smallprogramimg/fx_icon5.png",
			'images_48' => $prefix ."/smallprogramimg/fxtopbg.png",
			'images_49' => $prefix ."/smallprogramimg/go.png",
			'images_50' => $prefix ."/smallprogramimg/grid_icon_01.png",
			'images_51' => $prefix ."/smallprogramimg/grid_icon_02.png",
			'images_52' => $prefix ."/smallprogramimg/grid_icon_03.png",
			'images_53' => $prefix ."/smallprogramimg/grid_icon_04.png",
			'images_54' => $prefix ."/smallprogramimg/grid_icon_05.png",
			'images_55' => $prefix ."/smallprogramimg/grid_icon_06.png",
			'images_56' => $prefix ."/smallprogramimg/grid_icon_07.png",
			'images_57' => $prefix ."/smallprogramimg/grid_icon_08.png",
			'images_58' => $prefix ."/smallprogramimg/icon_01.png",
			'images_59' => $prefix ."/smallprogramimg/icon_02.png",
			'images_60' => $prefix ."/smallprogramimg/icon_03.png",
			'images_61' => $prefix ."/smallprogramimg/icon_04.png",
			'images_62' => $prefix ."/smallprogramimg/icon_05.png",
			'images_63' => $prefix ."/smallprogramimg/icon_addfile.png",
			'images_64' => $prefix ."/smallprogramimg/icon_addr.png",
			'images_65' => $prefix ."/smallprogramimg/icon_cart2.png",
			'images_66' => $prefix ."/smallprogramimg/icon_close.png",
			'images_67' => $prefix ."/smallprogramimg/icon_close2.png",
			'images_68' => $prefix ."/smallprogramimg/icon_cml.png",
			'images_69' => $prefix ."/smallprogramimg/icon_dd.png",
			'images_70' => $prefix ."/smallprogramimg/icon_ddd.png",
			'images_71' => $prefix ."/smallprogramimg/icon_del.png",
			'images_72' => $prefix ."/smallprogramimg/icon_edit.png",
			'images_73' => $prefix ."/smallprogramimg/icon_fenlei.png",
			'images_74' => $prefix ."/smallprogramimg/icon_gofl.png",
			'images_75' => $prefix ."/smallprogramimg/icon_gwc.png",
			'images_76' => $prefix ."/smallprogramimg/icon_hot.png",
			'images_77' => $prefix ."/smallprogramimg/icon_huangguan.png",
			'images_78' => $prefix ."/smallprogramimg/icon_iphone.png",
			'images_79' => $prefix ."/smallprogramimg/icon_kf.png",
			'images_80' => $prefix ."/smallprogramimg/icon_list1.png",
			'images_81' => $prefix ."/smallprogramimg/icon_list2.png",
			'images_82' => $prefix ."/smallprogramimg/icon_lock.png",
			'images_83' => $prefix ."/smallprogramimg/icon_new.png",
			'images_84' => $prefix ."/smallprogramimg/icon_phone.png",
			'images_85' => $prefix ."/smallprogramimg/icon_plus.png",
			'images_86' => $prefix ."/smallprogramimg/icon_qb.png",
			'images_87' => $prefix ."/smallprogramimg/icon_ren.png",
			'images_88' => $prefix ."/smallprogramimg/icon_search.png",
			'images_89' => $prefix ."/smallprogramimg/icon_search2.png",
			'images_90' => $prefix ."/smallprogramimg/icon_setting.png",
			'images_91' => $prefix ."/smallprogramimg/icon_share.png",
			'images_92' => $prefix ."/smallprogramimg/icon_shop.png",
			'images_93' => $prefix ."/smallprogramimg/icon_trash2.png",
			'images_94' => $prefix ."/smallprogramimg/icon_trash3.png",
			'images_95' => $prefix ."/smallprogramimg/icon_user.png",
			'images_96' => $prefix ."/smallprogramimg/icon_vip.png",
			'images_97' => $prefix ."/smallprogramimg/icon_x.png",
			'images_98' => $prefix ."/smallprogramimg/img-nav_icon1.png",
			'images_99' => $prefix ."/smallprogramimg/img-nav_icon2.png",
			'images_100' => $prefix ."/smallprogramimg/img-nav_icon3.png",
			'images_101' => $prefix ."/smallprogramimg/img-nav_icon4.png",
			'images_102' => $prefix ."/smallprogramimg/index88_03.png",
			'images_103' => $prefix ."/smallprogramimg/index99_03.png",
			'images_104' => $prefix ."/smallprogramimg/iocn_like1.png",
			'images_105' => $prefix ."/smallprogramimg/iocn_like2.png",
			'images_106' => $prefix ."/smallprogramimg/kouzi.png",
			'images_107' => $prefix ."/smallprogramimg/login_wx.png",
			'images_108' => $prefix ."/smallprogramimg/missed.png",
			'images_109' => $prefix ."/smallprogramimg/nodata1.png",
			'images_110' => $prefix ."/smallprogramimg/nodata2.png",
			'images_111' => $prefix ."/smallprogramimg/nodata3.png",
			'images_112' => $prefix ."/smallprogramimg/ok.png",
			'images_113' => $prefix ."/smallprogramimg/pay_icon01.png",
			'images_114' => $prefix ."/smallprogramimg/pay_icon02.png",
			'images_115' => $prefix ."/smallprogramimg/pay_icon03.png",
			'images_116' => $prefix ."/smallprogramimg/pinglun.png",
			'images_117' => $prefix ."/smallprogramimg/popts_icon_01.png",
			'images_118' => $prefix ."/smallprogramimg/popts_icon_02.png",
			'images_119' => $prefix ."/smallprogramimg/popts_icon_03.png",
			'images_120' => $prefix ."/smallprogramimg/popts_icon_04.png",
			'images_121' => $prefix ."/smallprogramimg/pyq.png",
			'images_122' => $prefix ."/smallprogramimg/qd_10.jpg",
			'images_123' => $prefix ."/smallprogramimg/qd2_03.png",
			'images_124' => $prefix ."/smallprogramimg/qdl.png",
			'images_125' => $prefix ."/smallprogramimg/rewm.png",
			'images_126' => $prefix ."/smallprogramimg/ruzhubg.png",
			'images_127' => $prefix ."/smallprogramimg/start1.png",
			'images_128' => $prefix ."/smallprogramimg/start2.png",
			'images_129' => $prefix ."/smallprogramimg/tabbar_icon01.png",
			'images_130' => $prefix ."/smallprogramimg/tabbar_icon01_hl.png",
			'images_131' => $prefix ."/smallprogramimg/tabbar_icon02.png",
			'images_132' => $prefix ."/smallprogramimg/tabbar_icon02_hl.png",
			'images_133' => $prefix ."/smallprogramimg/tabbar_icon03.png",
			'images_134' => $prefix ."/smallprogramimg/tabbar_icon03_hl.png",
			'images_135' => $prefix ."/smallprogramimg/tabbar_icon04.png",
			'images_136' => $prefix ."/smallprogramimg/tabbar_icon04_hl.png",
			'images_137' => $prefix ."/smallprogramimg/wddp_banner.png",
			'images_138' => $prefix ."/smallprogramimg/wdjf.png",
			'images_139' => $prefix ."/smallprogramimg/wdjfbg_b.png",
			'images_140' => $prefix ."/smallprogramimg/wdjfbg_t.png",
			'images_141' => $prefix ."/smallprogramimg/wdyg.png",
			'images_142' => $prefix ."/smallprogramimg/wdyj.png",
			'images_143' => $prefix ."/smallprogramimg/wuliucar.png",
			'images_144' => $prefix ."/smallprogramimg/wxhy.png",
			'images_145' => $prefix ."/smallprogramimg/z-cat.png",
			'images_146' => $prefix ."/smallprogramimg/z-z-fen.png",
			'images_147' => $prefix ."/smallprogramimg/zfok.png",
			'images_148' => $prefix ."/smallprogramimg/zfok2.jpg",
			'images_149' => $prefix ."/smallprogramimg/z-icon01.png",
			'images_150' => $prefix ."/smallprogramimg/z-icon02.png",
			'images_151' => $prefix ."/smallprogramimg/z-icon03.png",
			'images_152' => $prefix ."/smallprogramimg/z-icon04.png",
			'images_153' => $prefix ."/smallprogramimg/z-icon05.png",
			'images_154' => $prefix ."/smallprogramimg/z-shou.png",
			'images_155' => $prefix ."/smallprogramimg/z-tit01.png",
			'images_156' => $prefix ."/smallprogramimg/z-zhead.png",
			'images_157' => $prefix ."/smallprogramimg/z-zichongzhika.png",
		];

		DataReturn::returnJson('200','请求数据成功！',$res);
	}

}

?>